import apiClient, { API_URL } from "../api/inventory";

// Import the new, refined types
import { UnifiedInventoryItem } from '@/types/inventory';
const INVENTORY_BASE_URL = `${API_URL}/api/inventory-management`;

export interface DeleteResponse {
    message: string;
}

/**
 * Fetches all inventory items from the API.
 */
export const getInventoryItems = async (): Promise<UnifiedInventoryItem[]> => {
    const response = await apiClient.get(INVENTORY_BASE_URL);
    return response.data;
};

/**
 * Creates a new inventory item.
 * We use Omit to exclude fields typically generated by the backend (like id and timestamps).
 */
export const createInventoryItem = async (
    // Assuming the backend auto-generates 'id' and 'timestamp'
    item: Omit<UnifiedInventoryItem, 'id' | 'timestamp' | '_id'>
): Promise<UnifiedInventoryItem> => {
    const res = await apiClient.post(INVENTORY_BASE_URL, item);
    return res.data;
};


/**
 * Fetches a single inventory item by its ID.
 */
export const getInventoryItemById = async (id: string): Promise<UnifiedInventoryItem> => {
    const response = await apiClient.get(`${INVENTORY_BASE_URL}/${id}`);
    return response.data;
};

/**
 * Updates an existing inventory item by its ID.
 */
export const updateInventoryItem = async (
    id: string, 
    // Fix 1: The return type was 'InventoryItem', which isn't defined.
    // It should be 'UnifiedInventoryItem'.
    // Fix 2: The input type was using 'Omit' within 'Partial', which is redundant
    // if all properties are already optional with Partial. Cleaned up the Omit list.
    inventoryData: Partial<Omit<UnifiedInventoryItem, 'id' | '_id' | 'timestamp'>>
): Promise<UnifiedInventoryItem> => {
    const response = await apiClient.put(`${INVENTORY_BASE_URL}/${id}`, inventoryData);
    return response.data;
};

/**
 * Deletes an inventory item by its ID.
 */
export const deleteInventoryItem = async (id: string): Promise<DeleteResponse> => {
    const response = await apiClient.delete(`${INVENTORY_BASE_URL}/${id}`);
    return response.data;
};